---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: crc-support
  labels:
    app.kubernetes.io/version: "v2.0.0-dev"
    redhat.com/product: openshift-local
    dev.lifecycle.io/phase: testing
  annotations:
    tekton.dev/pipelines.minVersion: "0.44.x"
    tekton.dev/categories: "openshift-local"
    tekton.dev/tags: "openshift-local, testing"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task will prepare a target host with valid openshift local related assets

    It will download and install an specific Openshift Local version or can be used to download a specific bundle
  volumes:
    - name: host-secret
      secret:
        secretName: $(params.secret-host)
    - name: orsa-asset      
  
  params:
    # OS parameter
    - name: os
      description: type of platform per target host (windows, darwin or linux). Default linux
      default: linux
    - name: secret-host
      description: |
        ocp secret holding the hsot info credentials. Secret should be accessible to this task.
        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: XXXX
          labels:
            app.kubernetes.io/component: XXXX
        type: Opaque
        data:
          host: XXXX
          username: XXXX
          password: XXXX
          id_rsa: XXXX
          platform: XXXX
          os-version: XXXX
          arch: XXXX
          os: XXXX
    # Assets parameter
    - name: asset-base-url
      description: base url for the asset to be downloaded
      default: ""
    - name: asset-oras-address
      description: the oras address of the asset
      default: ""
    - name: asset-name
      description: name for the asset to be downloaded
    - name: asset-shasum-name
      description: file name for shasum to check asset
      default: sha256sum.txt
    - name: crc-version
      description: Optional parameter to give info about crc version managed as version is not present within the asset name.
      # Main stands for version being built from main of the head
      default: main
    # Control parameters
    - name: download
      description: controls if preparer will download the element
      default: 'true'
    - name: install
      description: controls if preparer will install. (In case of distriutable)
      default: 'true'
    - name: force-fresh
      description: controls if preparer will remove any previous existing crc version
      default: 'true'
    - name: delete
      description: controls if preparer will remove the previous downloaded folders
      default: 'false'
    - name: debug
      description: increase verbosity
      default: 'false'

  results:
    - name: target-path
      description: Path on target host where the item has been dowloaded
    
  steps:
  - name: oras-pull
    image: ghcr.io/oras-project/oras:v1.2.3
    when:
      - input: "$(params.asset-oras-address)"
        operator: notin
        values: [""]
    volumeMounts:
      - name: orsa-asset
        mountPath: /workspace
    args: 
      - pull
      - $(params.asset-oras-address) 
  - name: preparer
    image: quay.io/crc-org/ci-crc-support:v2.0.0-dev-$(params.os) 
    imagePullPolicy: Always
    volumeMounts:
      - name: host-secret
        mountPath: /opt/host
      - name: orsa-asset
        mountPath: /opt/asset
    script: |
      #!/bin/bash
      set -x

      if [ "$(params.debug)" = "true" ]; then
        set -xuo 
      fi

      # Prepare ENVs
      SECONDS=0
      DEBUG=$(params.debug)
      TARGET_HOST=$(cat /opt/host/host)
      TARGET_HOST_USERNAME=$(cat /opt/host/username)
      cp /opt/host/id_rsa id_rsa
      chmod 600 id_rsa
      TARGET_HOST_KEY_PATH=id_rsa
      TARGET_FOLDER=crc-support-$RANDOM$RANDOM
      TARGET_CLEANUP='true'
      
      # Create cmd per OS
      runner="run.sh"
      if [[ $(params.os) == "windows" ]]; then
        runner="run.ps1"
      fi
      # Path for assets on remote target
      tPath="/Users/${TARGET_HOST_USERNAME}/OpenshiftLocal"
      if [[ $(params.os) == 'linux' ]]; then
        tPath="/home/${TARGET_HOST_USERNAME}/OpenshiftLocal"
      fi
      
      
      if [[ $(params.asset-name) == *'.crcbundle' ]]; then
        # It is bundle
        name=$(params.asset-name)
        nameArr=(${name//_/ })
        if [[ $(params.asset-name) == *'microshift'* ]]; then
          tPath+="/bundle/microshift/${nameArr[3]}"
        else
          tPath+="/bundle/openshift/${nameArr[2]}"
        fi
      else
        tPath+="/crc/$(params.crc-version)"
      fi

      download=$(params.download)
      
      if [[ -f /opt/asset/$(params.asset-name) ]]; then
        echo "copy $(params.asset-name) to /opt/crc-support" 
        cp /opt/asset/$(params.asset-name) /opt/crc-support
        ls /opt/crc-support
        download="false"
        
        tPath="/Users/${TARGET_HOST_USERNAME}/${TARGET_FOLDER}"
        if [[ $(params.os) == 'linux' ]]; then
          tPath="/home/${TARGET_HOST_USERNAME}/${TARGET_FOLDER}"
        fi

      else
        echo "$(params.asset-name) not found"
      fi


      cmd="${TARGET_FOLDER}/${runner} -targetPath $tPath "
      cmd+="-aBaseURL $(params.asset-base-url) "
      cmd+="-aName $(params.asset-name) "
      cmd+="-aSHAName $(params.asset-shasum-name) "
      cmd+="-freshEnv $(params.force-fresh) "
      cmd+="-download $download "
      cmd+="-install $(params.install) "
      cmd+="-delete $(params.delete) "
      
      # Exec
      . entrypoint.sh "${cmd}"

      # Results
      echo -n "$tPath" | tee $(results.target-path.path)

    resources:      
      requests:
        memory: "100Mi"
        cpu: "50m"
      limits:
        memory: "140Mi"
        cpu: "100m"
    timeout: 60m
  