---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: crc-builder-installer-macos-
spec:
  taskRef:
    name: crc-builder-installer
  params:
  - name: platform
    value: macos
  - name: crc-scm-pr
    value: '2971'
  - name: host-config-secret
    value: host-mac-1-brno
  timeout: 90m
