---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: crc-qe-virtualized
  labels:
    app.kubernetes.io/version: "0.5"
    redhat.com/product: openshift-local
    redhat.com/phase: qe
  annotations:
    tekton.dev/pipelines.minVersion: "0.24.x"
    tekton.dev/categories: qe
    tekton.dev/tags: openshift-local, qe, nested virualization
    tekton.dev/displayName: "qe for openshift local"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This pipeline will run the testing for openshift local on 
    a specific linux version based on nested virtualization

  workspaces:
  - name: pipelines-data

  params:
  - name: target-platform
    description: param to inform on which platform will act the pipeline (windows, darwin or linux)
    default: linux

  # Windows related params
  - name: windows-featurepack
    description: windows feature pack (default "22h2-pro")
    # default: 22h2-pro 
    default: ''
  - name: windows-version
    description: Major version for windows desktop 10 or 11 (default "11")
    # default: '11'
    default: ''
  - name: windows-vmsize
    description: Size of azure machine for running the windows system
    default: Standard_D8ds_v4
 
  # Fedora related params
  - name: fedora-version
    description: in case requestedHostID set to ol-fedora this param will control the major fedora version (i.e 37, 38,...)
    default: ''
  # Rhel related params
  - name: rhel-version
    default: ''
  - name: repo-baseos-url
    description: baseos repo url to setup on provisioned machine
    default: ''
  - name: repo-appstream-url
    description: appstream repo url to setup on provisioned machine
    default: ''
  - name: rh-account-secret
    description: ocp secret holding the credentials for a valid rh user to subscribe VM. Secret should be accessible to this task.
    default: credentials-rh-subs-crcqe-prod
  - name: image-id
    description: internal id for image on virtualization provider (Openstack image ID)
    default: ''

  # Cloud providers creds
  - name: azure-credentials-secret
    description: ocp secret holding the azure credentials. Secret should be accessible to this task.
    default: az-crcqe-bot
  - name: aws-credentials-secret
    description: secret holding credentials to create infra on aws
    default: aws-crcqe-bot

  # CRC params
  - name: internal-base-url
    description: in case of an internal release we can not directly download it but upload fisrt to s3. This setup the base url for the assets to be uploaded
    default: "''"
  - name: internal-asset-name
    description: asset name to be uploaded 
    default: "''"
  - name: internal-shasum-name
    description: shasum name to be uploaded 
    default: "''"
  - name: internal-shasum-target-name
    description: setup the name for the internal shasum on s3
    default: "''"
  - name: downloadable-url
    description: full base url to download ditributables and shasumsfiles
    default: ''
  - name: shasum-file
    description: file name for shasum to check distributable
    default: sha256sum.txt

  # QE params
  - name: e2e-tag
    description: tags to select e2e scnearios. Default empty values which means all scnearios  
    default: "''"  
  - name: qe-worspace-subpath
    description: subpath on workspace where storing ephemeral qe results
    default: qe-results
  - name: run-e2e
    description: Control if e2e tests are executed. (true or false)
    default: 'true'
  - name: run-integration
    description: Control if integration tests are executed. (true or false)
    default: 'true'

  # S3 params (Storage results)
  - name: s3-data-secret
    default: datalake-aws
  - name: s3-bucket
    default: crcqe-asia
  - name: s3-folder-path
    description: target folder to store results. (Example release/2.9.0)

  # Pipeline control params
  - name: debug
    description: control verbosity and keep instances after run for troubleshooting. 
    default: 'false'
  
  results:
  - name: results-url
    description: url to get results for the execution
    value: $(tasks.url-generator.results.url)
  - name: product-version
    description: product version tested for this interop 
    value: $(tasks.crc-info.results.crc-version)
  - name: qe-duration
    description: amount of time in seconds for qe execution (testing) 
    value: $(tasks.qe.results.duration)

  tasks:
  - name: correlate
    taskRef:
      name: gather-run-info
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
  - name: s3-info
    runAfter:
    - correlate
    taskRef:
      name: gather-s3-info
    params:
    - name: s3-data-secret
      value: $(params.s3-data-secret) 
    - name: bucket
      value: $(params.s3-bucket) 
    - name: folder-path
      # only one have value fedora-version or rhel-version
      value: $(params.s3-folder-path)/$(params.fedora-version)$(params.rhel-version)$(params.windows-version)$(params.windows-featurepack)
  - name: internal-asset-upload
    when: 
    - input: $(params.internal-base-url)  
      operator: notin
      values: ["''"]
    - input: $(params.internal-asset-name)  
      operator: notin
      values: ["''"]
    runAfter:
    - s3-info
    taskRef:
      name: s3-sync-http
    params:
    - name: asset-url
      value: $(params.internal-base-url)/$(params.internal-asset-name)
    - name: s3-url
      value: $(tasks.s3-info.results.upload-url)
    - name: s3-access-key
      value: $(tasks.s3-info.results.access-key)
    - name: s3-secret-key
      value: $(tasks.s3-info.results.secret-key)
    - name: s3-folder-path
      value: $(tasks.s3-info.results.upload-path)
    - name: s3-asset-name
      value: $(params.internal-asset-name)
    timeout: "15m"
  - name: internal-shasum-upload
    when: 
    - input: $(params.internal-base-url)  
      operator: notin
      values: ["''"]
    - input: $(params.internal-shasum-name)  
      operator: notin
      values: ["''"]
    runAfter:
    - s3-info
    taskRef:
      name: s3-sync-http
    params:
    - name: asset-url
      value: $(params.internal-base-url)/$(params.internal-shasum-name)
    - name: s3-url
      value: $(tasks.s3-info.results.upload-url)
    - name: s3-access-key
      value: $(tasks.s3-info.results.access-key)
    - name: s3-secret-key
      value: $(tasks.s3-info.results.secret-key)
    - name: s3-folder-path
      value: $(tasks.s3-info.results.upload-path)
    - name: s3-asset-name
      value: $(params.internal-shasum-name)
    timeout: "15m"
  - name: url-picker
    runAfter:
      - s3-info
    taskRef:
      name: url-picker
    params:
    - name: internal-base-url
      value: $(params.internal-base-url)
    - name: public-base-url
      value: $(tasks.s3-info.results.download-url)
    - name: external-base-url
      value: $(params.downloadable-url)  
  - name: crc-info
    runAfter:
    - correlate
    taskRef:
      name: gather-crc-info
    params:
    - name:  platform
      value: $(params.target-platform)
  - name: provision-fedora
    runAfter:
    - s3-info
    - crc-info
    taskRef:
      resolver: bundles 
      params:
      - name: bundle
        value: quay.io/rhqp/qenvs-tkn:v0.0.4-snapshot
      - name: name
        value: infra-management-aws
      - name: kind
        value: task
    when: 
    - input: $(params.fedora-version)  
      operator: notin
      values: ['']
    params:
    # Need to export the variable to control fedora version
    # for time being it only check 37
    # - name: fedora-version
    #   value: $(params.fedora-version)
    - name: project-name
      value: crc-qe-virtualized-fedora-$(tasks.correlate.results.correlation)
    - name: requestedHostID
      value: ol-fedora
    - name: fedora-version
      value: $(params.fedora-version)  
    - name: operation
      value: create
    - name: aws-credentials-secret
      value: $(params.aws-credentials-secret) 
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    # TODO need to make this optional on the task, only required for rhel 
    - name: rh-account-secret
      value: $(params.rh-account-secret)
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "20m" 
  - name: provision-rhel
    runAfter:
    - s3-info
    - crc-info
    when: 
    - input: $(params.rhel-version)  
      operator: notin
      values: ['']
    taskRef:
      name: infra-rhel-provision
    params:
    - name: id
      value: crc-qe-virtualized-rhel
    - name: rhel-version
      value: $(params.rhel-version)
    - name: repo-baseos-url
      value: $(params.repo-baseos-url)
    - name: repo-appstream-url
      value: $(params.repo-appstream-url)
    - name: rh-account-secret
      value: $(params.rh-account-secret)
    - name: image-id
      value: $(params.image-id)
    - name: correlation
      value: $(tasks.correlate.results.correlation)
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "45m" 
  - name: provision-windows
    runAfter:
    - s3-info
    - crc-info
    when: 
    - input: $(params.windows-featurepack)  
      operator: notin
      values: ['']
    - input: $(params.windows-version)  
      operator: notin
      values: ['']
    taskRef:
      resolver: bundles 
      params:
      - name: bundle
        value: quay.io/rhqp/qenvs-tkn:v0.0.4-snapshot
      - name: name
        value: infra-management-azure
      - name: kind
        value: task
    params:
    - name: project-name
      value: podman-backend-qe-$(tasks.correlate.results.correlation)
    - name: operation
      value: create
    - name: windows-featurepack
      value: $(params.windows-featurepack) 
    - name: windows-version
      value: $(params.windows-version) 
    - name: vmsize
      value: $(params.windows-vmsize) 
    - name: credentials-secret
      value: $(params.azure-credentials-secret) 
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "20m" 
  - name: sync-provision
    runAfter:
    - provision-fedora
    - provision-rhel
    - provision-windows
    taskRef:
      name: infra-syncer
    params:
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "20m" 
  - name: install
    runAfter:
    - sync-provision
    - internal-asset-upload
    - internal-shasum-upload
    taskRef:
      resolver: bundles 
      params:
      - name: bundle
        value: quay.io/rhqp/crc-support-tkn:v0.3
      - name: name
        value: crc-support
      - name: kind
        value: task
    params:
    - name: os
      value: $(params.target-platform)  
    - name: host
      value: $(tasks.sync-provision.results.host)
    - name: username
      value: $(tasks.sync-provision.results.username)
    - name: key
      value: $(tasks.sync-provision.results.key-filename)
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    # Preparing crc version is only used for target path storage  
    - name: downloadable-version
      value: $(tasks.crc-info.results.crc-version)    
    - name: downloadable-url
    # Only accessible url within downloadable-url or internal uploaded composed url  
      value: $(tasks.url-picker.results.base-url)
    - name: shasum-file
      value: $(params.shasum-file)  
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "1h"  
  - name: qe
    runAfter:
    - install
    taskRef:
      name: crc-qe-cli
    params:
    - name: platform
      value: $(params.target-platform)  
    - name: ip
      value: $(tasks.sync-provision.results.host)
    - name: username
      value: $(tasks.sync-provision.results.username)
    - name: key
      value: $(tasks.sync-provision.results.key-filename)
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    - name: worspace-qe-subpath
      value: $(params.qe-worspace-subpath)
    # This is used to run e2e and integration containers
    # Need to integrate a build from main and make it accessible
    # For the time been we are good with latest released version
    - name: crc-version
      value: $(tasks.crc-info.results.crc-version)
    - name: run-e2e
      value: $(params.run-e2e) 
    - name: e2e-tag
      value: $(params.e2e-tag) 
    - name: run-integration
      value: $(params.run-integration) 
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "5h"   
  - name: datalake-sink
    runAfter:
    - qe
    taskRef:
      name: s3-sink-workspace
    params:
    - name: s3-url
      value: $(tasks.s3-info.results.upload-url)
    - name: s3-access-key
      value: $(tasks.s3-info.results.access-key)
    - name: s3-secret-key
      value: $(tasks.s3-info.results.secret-key)
    - name: s3-folder-path
      value: $(tasks.s3-info.results.upload-path)
    - name: workspace-path
      value: $(tasks.correlate.results.workspace-resources-path)
    - name: workspace-subpath
      value: $(params.qe-worspace-subpath) 
    # Do not delete to keep tf state to decomission on final 
    # This task should be splitted to allow only cleaning up
    - name: workspace-cleanup
      value: 'false'
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "15m"
  - name: url-generator
    taskRef:
      name: url-generator
    runAfter:
    - datalake-sink
    params:
    - name: base-url
      value: $(tasks.s3-info.results.download-url)
    - name: context
      value: $(params.qe-worspace-subpath)
    - name: asset-name
      value: e2e-non-ux.xml
  finally:
  - name: debug-info
    when: 
    - input: $(params.rhel-version)  
      operator: notin
      values: ['']
    - input: $(params.debug)
      operator: in
      values: ["true"]
    taskSpec:
      workspaces:
      - name: pipelines-data
      params:
      - name: workspace-resources-path
        description: path relative to workspace where to store keys
      steps:
      - name: show-denug-info
        image: registry.access.redhat.com/ubi9/ubi-minimal
        script: |
          #!/bin/sh
          workspace_path=$(workspaces.pipelines-data.path)/$(params.workspace-resources-path)
          echo "private key"
          cat ${workspace_path}/id_rsa
          echo "host"
          cat ${workspace_path}/host
          echo "username"
          cat ${workspace_path}/username
    params:
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
  - name: decomission-fedora
    when: 
    - input: $(params.fedora-version)  
      operator: notin
      values: ['']
    taskRef:
      resolver: bundles 
      params:
      - name: bundle
        value: quay.io/rhqp/qenvs-tkn:v0.0.4-snapshot
      - name: name
        value: infra-management-aws
      - name: kind
        value: task
    params:
    - name: project-name
      value: crc-qe-virtualized-fedora-$(tasks.correlate.results.correlation)
    - name: requestedHostID
      value: ol-fedora
    - name: operation
      value: destroy
    - name: aws-credentials-secret
      value: $(params.aws-credentials-secret) 
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    # TODO need to make this optional on the task, only required for rhel 
    - name: rh-account-secret
      value: $(params.rh-account-secret)
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "15m"  
  - name: decomission-rhel
    when: 
    - input: $(params.rhel-version)  
      operator: notin
      values: ['']
    - input: $(params.debug)
      operator: in
      values: ["false"]
    taskRef:
      name: infra-rhel-decommission
    # not supported yet
    # onError: continue
    params:
    - name: infra-id
      # This is the value composed on infra provision for project
      # if we keep the link with provision task if it fails this one will not run
      value: crc-qe-virtualized-rhel-$(tasks.correlate.results.correlation)
    - name: rhel-version
      value: $(params.rhel-version)
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "15m"  
  - name: decomission-windows
    when: 
    - input: $(params.windows-featurepack)  
      operator: notin
      values: ['']
    - input: $(params.windows-version)  
      operator: notin
      values: ['']
    taskRef:
      resolver: bundles 
      params:
      - name: bundle
        value: quay.io/rhqp/qenvs-tkn:v0.0.4-snapshot
      - name: name
        value: infra-management-azure
      - name: kind
        value: task
    params:
    - name: project-name
      value: podman-backend-qe-$(tasks.correlate.results.correlation)
    - name: operation
      value: destroy
    - name: credentials-secret
      value: $(params.azure-credentials-secret) 
    - name: workspace-resources-path
      value: $(tasks.correlate.results.workspace-resources-path)
    workspaces:
    - name: pipelines-data
      workspace: pipelines-data
    timeout: "15m"  

    