name: oci-builds

on:
  push:
    branches: [ main ]
    tags:        
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-mapt:
    name: build-mapt
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build image for PR
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        SNC_RUNNER=ghcr.io/crc-org/ci-definitions SNC_RUNNER_V=pr-${{ github.event.number }} make oci-build

    