name: opensearch-pusher

on:
  workflow_run:
    workflows: [ 'opensearch-builder' ]
    types:
      - completed
  
jobs:
  push:
    name: push
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download opensearch assets
        uses: actions/download-artifact@v4
        with:
          name: opensearch
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Get opensearch build informaiton
        run: |
          echo "source_event=$(cat opensearch-build-event)" >> "$GITHUB_ENV"
          echo "image=$(cat opensearch-image)" >> "$GITHUB_ENV"

      - name: Log in to ghcr.io
        if: ${{ env.source_event == 'pull_request' }}
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in quay.io
        if: ${{ env.source_event == 'push' }}
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}

      - name: Push reportportal
        run: |
          # Load 
          podman load -i opensearch.tar 
          # Push
          podman push ${{ env.image }}

      